### PR TITLE
created login, signup with email functionality and created component …

### PR DESCRIPTION
**Pull request by anshul45**
closed [[Login Page #2]](https://github.com/Dominate-X-Club/Copod/issues/2)

Created login, signup, and protected page functionality. Since there is no user details component or icon, I left out the logout functionality for now. When it becomes available in the UI, I will create another pull request with the logout functionality.

### CODE REVIEW

**Comment by iAbhinav** [comment]
Hey @code-withAshish can you review

**Comment by code-withAshish** [comment]
> Hey @code-withAshish can you review

Yes I am keeping my eye on this , actually lakshya made a very good matching theme login page also, he will also file the problem soon, so I am waiting for all the responses.
But I'll check this one out.

**Comment by iAbhinav** [comment]
Ok cool

**Comment by code-withAshish** [comment]
@netlify /

**Comment by code-withAshish** [comment]
@anshul45 could you please put a video of the working site, so we know how it looks that way it becomes easy for us to review your changes.

**Comment by anshul45** [comment]
If we click verify email it redirect to auth/confirm and verify user and log in. We don't need to login again it login with that code only

https://github.com/Dominate-X-Club/Copod/assets/80778090/9b5dcccd-4c65-4ac0-a57e-7fbfd7ae9d8a

**Comment by code-withAshish** [comment]
Hey @anshul45 it looks good, but the design is fairly simple and looks very empty and some parts of your code needs improvement, but in the meanwhile we got another PR that fits our requirement so we will be moving on with that.
Thank you for your effort and contribution.

**Pull request closed without merging**
