### PR TITLE
 feat(landing): Implement Landing Page for Copod

### PR DESCRIPTION
**Pull request by Iamanshuaditya**
This pull request addresses the issue #1, which involves creating the landing page for Copod, a managed podcast recording studio located in New Delhi.
Refs: #1

### CODE REVIEW

**Comment by code-withAshish** [comment]
Please attach a screenshot showcasing your entire design, that way it's easier for us to judge it.
Thank you

**Comment by rohitt-gupta** [comment]
Hi @Iamanshuaditya ,
PR looks good. 

As mentioned in the issue, it is 10$ bounty, will not be increased!

there are few issues in the your deployed version , please fix them!

1. Make the landing page like modern designs which contains centered CTA buttons and H! just like @iAbhinav mentioned in below thread https://github.com/Dominate-X-Club/Copod/issues/1#issuecomment-2096455967

2. Set a limit to max width in tailwind it may be max-w-7xl or 8xl , and mx-auto to make it centered. Do not cover full width of the window/parent container.

3. Footer is broken and moves along with the view
image

4. Use less fancy animations. Too much animations are being used!

5. Could use the header / nav as fixed!

These some of the suggestions which may make your solution more modern.

Try to take some inspiration from ui.aceternity.com

**Comment by iAbhinav** [comment]
Hey guys, copod is a "Venue" for podcasts, and not a podcast itself. We do not have episodes or voices

**Comment by code-withAshish** [comment]
as landing page is actively being developed by @iAbhinav and initial version has been merged in the main branch this PR is stale now , hence I am closing it.

**Pull request closed without merging**
